version: '3.6'
services:
  web:
    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
      target: production
    container_name: admissibles_php_74
    depends_on:
      - db
    ports:
      - 8123:80
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      GMAIL_PASSWORD: $GMAIL_PASSWORD
      DEBUG: $DEBUG
  db:
    restart: always
    container_name: admissibles_mysql8
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 6036:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./php/conf_server/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    restart: always
    container_name : admissibles_phpmyadmin
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: db
    ports:
      - 8124:80
    depends_on:
      - db 