version: '3.3'

volumes:
  models:
    external: false

services:
  web:
    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: admissibles_php_74
    depends_on:
      - db
    ports:
      - 8123:80
    environment:
      - mysql_password=${mysql_password}
      - gmail_password=${gmail_password}
  db:
    restart: always
    container_name: admissibles_mysql8
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_password}
      MYSQL_DATABASE: admissibles
      MYSQL_USER: admissibles_user
      MYSQL_PASSWORD: ${mysql_password}
    ports:
      - 6036:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./php/conf_server/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    restart: always
    container_name : admissibles_phpmyadmin
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: db
    ports:
      - 8124:80
    depends_on:
      - db 

  optimizer:
    build:
      context: ./gurobi
      dockerfile: Dockerfile
    volumes:
      - models:/models:ro
      - ./gurobi/gurobi.lic:/opt/gurobi/gurobi.lic:ro